services:
  rabbit:
    image: rabbitmq:latest
    restart: always

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - 5421:5432
